### ISSUE TITLE
dodać

### ISSUE THREAD

**Issue by klosiak** [pawellen/DataTablesListing#3]
sir please add row_id to tr, when the table is beeing generated

``` javascript
{
      "DT_RowId": "row_5",
      "first_name": "Airi",
      "last_name": "Satou",
      "position": "Accountant",
      "office": "Tokyo",
      "start_date": "28th Nov 08",
      "salary": "$162,700"
    },
```

more here > https://datatables.net/examples/server_side/ids.html

**Comment by pawellen** [comment]
Done. There is new listing option:
 'tr' => array(
    'id'    => null,
    'class' => null
),

id - is a property path of value that you want to add id string
class - is a string added to each row

egzample:
 'tr' => array(
    'id'    => 'id', //will generate id: LISTING_NAME_row_ID
    'class' => 'my-row-class' // will generate my-row-class to each row
),
