### ISSUE TITLE
tr atributes differ

### ISSUE THREAD

**Issue by klosiak** [pawellen/DataTablesListing#8]
tr attribute when loading throug ajax are diffrend then loading from twig

**Comment by pawellen** [comment]
Use "row_attr" option istead. You can pass there array of your custom tr attributes. Example for onclick attribute:

``` php
'row_attr' => array(
                'onclick' => function(MediaSubject $row) {
                    $url = $this->router->generate('media_subject_show', array(
                        'id' => $row->getId()
                    ), true);

                    return 'document.location = \'' . htmlspecialchars($url) . '\'';
                }
            )
```

Why should not add custom attributes inside twig template? Becouse it will be rendered only first time by PHP (when defer_load is false). All tatatable communication with server side is done by JSON and custom attributes must be included inside that json with don support html of tr tag.
