### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'p0_.id' in 'order clause' 

### ISSUE THREAD

**Issue by rstruniawski** [pawellen/DataTablesListing#9]
after updating doctrine/common and doctrine/orm to v2.5.0 the 'order_by' option generates exception SQLSTATE[42S22]: Column not found: 1054 Unknown column 'p0_.id' in 'order clause'

**Comment by pawellen** [comment]
I have doctrine doctrine/orm (v2.5.0) i all of my listing in that project works fine. Please check if entities are okej, maybe query You build using QueryBuilder is incorrect.
"Column not found" error suggest that you have error in orm mapping or you are trying to sort by non-existing column.
